### ISSUE TITLE
How to bypass Stripe Authentification and other questions

### ISSUE THREAD

**Issue by robin-moser** [thomas-illiet/feedbin-docker#3]
Hi,

first of all, thank you for sharing this project!

I'm trying to setup feedbin on a docker swarm network. After a few changed settings, I'm able to get the signin/register mask of feedbin. When trying to register, I run into a 500 Server error with following servererror messages:
```
I, [2019-03-25T10:38:41.253935 #29]  INFO -- : method=POST path=/users format=html controller=UsersController action=create status=500 error='Stripe::AuthenticationError: No API key provided. Set your API key using "Stripe.api_key = <API-KEY>". You can generate API keys from the Stripe web interface. See https://stripe.com/api for details, or email support@stripe.com if you have any questions.' duration=239.18 view=0.00 db=14.07
F, [2019-03-25T10:38:41.256007 #29] FATAL -- :   ,
F, [2019-03-25T10:38:41.255978 #29] FATAL -- : Stripe::AuthenticationError (No API key provided. Set your API key using "Stripe.api_key = <API-KEY>". You can generate API keys from the Stripe web interface. See https://stripe.com/api for details, or email support@stripe.com if you have any questions.):,
F, [2019-03-25T10:38:41.255893 #29] FATAL -- :   ,
F, [2019-03-25T10:38:41.256032 #29] FATAL -- : app/models/customer.rb:8:in `create',
```

Can you tell me, what has gone wrong? Did i miss something?

In addition, I have a few more questions about the configuration:

1. `SECRET_KEY_BASE`:
Is a string generated by `openssl rand -hex 64` enough? 
    
1. `AWS_ACCESS_KEY_ID`, `AWS_S3_BUCKET`, `AWS_SECRET_ACCESS_KEY`:
For what features are the AWS keys? Do I need them? (I don't host in AWS)

1. `CAMO_HOST`, `CAMO_KEY`:
What to enter here? A random string for the key and an arbitrary host name?

1. `DEFAULT_URL_OPTIONS_HOST: feedbin.netboot.fr`:
What's that for? 

1. `FROM_ADDRESS`, `PUSH_URL`:
What to enter here?

1. `SMTP_ADDRESS`, `SMTP_PASSWORD`, `SMTP_USERNAME`:
Do I necessary need SMTP? 

It would be really cool if you find some time answering the questions or helping me to find the answers myself.

Thanks in advance!

**Comment by norweeg** [comment]
If it helps, you could use https://github.com/wader/postfix-relay for SMTP.  You can also use [Mailgun](https://www.mailgun.com/)'s free-tier too.  Not all my services can authenticate to an smtp, so I run the postfix-relay as an open smtp internally and it forwards everything through Mailgun.

**Comment by somedevreally** [comment]
yes if someone can answer these

**Comment by gglanzani** [comment]
@thomas-illiet Was is this closed? I'm getting the same STRIPE_API issue here :)

**Comment by thomas-illiet** [comment]
hello @gglanzani, because this feature is documented in the official repository :)

**Comment by gglanzani** [comment]
Hi @thomas-illiet thanks for the swift reply.

I thought that this project did not need the stripe keys (plus a modification of the docker-compose would be needed if that's not the case anymore).

I've tried to add my stripe keys (and modifying the docker-compose part) but it still complain that it cannot find the `trial` "feature" in my stripe account. So I guess there's still something extra besides adding the API key.

**Comment by angristan** [comment]
Hello,

I'm confused too. I have the same issues as OP, even though the README says:

> Will work without a payment system like stripe

What can we do to bypass this?

**Comment by angristan** [comment]
FWIW I made some PRs to Feedbin to improve self-hosted compatibility (including this Stripe thing). I also made https://github.com/angristan/feedbin-docker which I can attest works 100% since I'm currently running it as my own Feedbin instance.

**Comment by somedevreally** [comment]
ok great @angristan 
just now tried to clone the feedbin-docker it ask for github login and after that it says invalid on docker prompt

**Comment by angristan** [comment]
@somedevreally please open an issue there
