### ISSUE TITLE
docker pull error

### ISSUE THREAD

**Issue by somedevreally** [thomas-illiet/feedbin-docker#6]
```
Pulling feedbin (thomas-illiet/feedbin:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling feedbin (thomas-illiet/feedbin:)...
ERROR: pull access denied for thomas-illiet/feedbin, repository does not exist or may require 'docker login'

```

**Comment by thomas-illiet** [comment]
Hello @somedevreally, I will soon recreate this project, I first finished the creation of my kubernetes infrastructure :/

**Comment by somedevreally** [comment]
awesome and Thank you appreciate all the efforts

**Comment by simon-wessel** [comment]
It works if you remove the hyphen in `thomas-illiet/feedbin` in `docker-compose.yml`.

**Comment by somedevreally** [comment]
cool, that worked. 
but i cant get feedbin up, could be all the configuration with AWS/CAMO which i dont have or need.
anyways thanks
